In [155]:
import pandas as pd
from statsmodels.tsa.stattools import adfuller
import numpy as np

In [121]:
fx = pd.read_csv(r'/Users/hedonglin/Desktop/project/forex/fx_wrds_frbr/fx_rate_daily.csv')
ir = pd.read_csv(r'/Users/hedonglin/Desktop/project/forex/fx_wrds_frbr/interest_rate_daily.csv')

In [ ]:
fx.shape
fx.date
fx.dexcaus
fx.columns

Index(['date', 'dexusal', 'dexalus', 'dexbzus', 'dexcaus', 'dexchus',
       'dexdnus', 'dexhkus', 'dexinus', 'dexjpus', 'dexkous', 'dexmaus',
       'dexmxus', 'dexusnz', 'dexnzus', 'dexnous', 'dexsius', 'dexsfus',
       'dexslus', 'dexsdus', 'dexszus', 'dextaus', 'dexthus', 'dexusuk',
       'dexukus', 'dexvzus', 'exauus', 'exbeus', 'exfnus', 'exfrus', 'exgeus',
       'exgrus', 'exusir', 'exirus', 'exitus', 'exneus', 'expous', 'exspus',
       'exusec', 'execus', 'dexuseu', 'dexeuus', 'dtwexb', 'dtwexbgs',
       'dtwexm', 'dtwexafegs', 'indexgx', 'dtwexo', 'dtwexemegs'],
      dtype='str')

In [116]:
df2 = fx.dropna(subset = ['execus','exusec'])

In [ ]:
# Check Stationarity. These forex show non-stationarity

In [152]:
result = adfuller(df2['gbp'])

print("ADF statistic:", result[0])
print("p-value:", result[1])

ADF statistic: -1.237183318126381
p-value: 0.6573994370832356

In [165]:
# df3 = df2[['gbp', 'eur', 'chf']].pct_change()
df4 = np.log(df2[['gbp', 'eur', 'chf']]).diff()
df4 = df4.dropna()
print(df4)

            gbp       eur       chf
7363   0.000905  0.004412  0.002047
7364   0.001148  0.010600  0.011472
7365   0.003148 -0.003089  0.000794
7366   0.005471  0.010161  0.007689
7367   0.001830  0.001733 -0.000501
...         ...       ...       ...
14110  0.004671  0.011897  0.005596
14111 -0.007879 -0.009876 -0.008903
14112 -0.002320 -0.003847 -0.005424
14113  0.006493  0.004907  0.005093
14114  0.003141  0.003769  0.005067

[6545 rows x 3 columns]

In [166]:
df4.corr()

          gbp       eur       chf
gbp  1.000000  0.641931  0.506191
eur  0.641931  1.000000  0.785225
chf  0.506191  0.785225  1.000000

In [141]:
df2['gdp']

KeyError: 'gdp'

In [ ]:
fx_eurusd = fx.dropna(subset = ['date', 'dexusal','dexbzus'])

In [135]:
df = fx.dropna(subset = ['dexeuus', 'dexukus', 'dexszus']).sort_values(by = 'date') # eur, gbp, chf
df2 = df[['date','dexeuus', 'dexukus', 'dexszus']]
df2 = df2.rename(columns = {'dexeuus': 'eur', 'dexukus': 'gbp', 'dexszus': 'chf'})

print(df2)

             date       eur       gbp     chf
7362   1999-01-04  0.846597  0.603100  1.3666
7363   1999-01-05  0.850340  0.603646  1.3694
7364   1999-01-06  0.859402  0.604339  1.3852
7365   1999-01-07  0.856751  0.606244  1.3863
7366   1999-01-08  0.865501  0.609570  1.3970
...           ...       ...       ...     ...
14110  2025-02-03  0.973047  0.807168  0.9139
14111  2025-02-04  0.963484  0.800833  0.9058
14112  2025-02-05  0.959785  0.798977  0.9009
14113  2025-02-06  0.964506  0.804182  0.9055
14114  2025-02-07  0.968148  0.806712  0.9101

[6546 rows x 4 columns]

# descriptive statistics

In [136]:
df2[['eur', 'gbp', 'chf']].corr()

          eur       gbp      chf
eur  1.000000  0.514907  0.58163
gbp  0.514907  1.000000 -0.30561
chf  0.581630 -0.305610  1.00000